version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/hpc-lab-maker
permissions:
  - object: /webapps/hpc-lab-maker/bin
    pattern: "*"
    except: ["activate*"]
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: bin/hpclab-beforeinstall.sh
  ApplicationStart:
    - location: bin/hpclab-start.sh
  ApplicationStop:
    - location: bin/hpclab-stop.sh
