version: 0.1

phases:
  install:
    commands:
      - yum install -y binutils cracklib-devel gcc python27-devel
      - python2.7 ./get-pip.py
      - pip install virtualenv
  pre_build:
    commands:
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - python -m py_compile ./labcafe.py
  post_build:
    commands:
      - rm -f aws-lab-cafe.zip
      - zip aws-lab-cafe.zip ./labcafe.pyc ./labcafe.py ./zappa_settings.json
      - zip aws-lab-cafe.zip venv/lib/python2.7/site-packages

artifacts:
  files:
    - aws-lab-cafe.zip
    - aws-lab-cafe.cfn
