version: 0.1

phases:
  install:
    commands:
      - yum install -y autoconf automake binutils cracklib-devel gcc python27-devel zip
      - python2.7 ./get-pip.py
      - pip install awscli virtualenv
      # PuTTY wants Automake-1.14, but we only have 1.13 (and it's good enough)
      - ln -s aclocal /usr/bin/aclocal-1.14
      - ln -s automake /usr/bin/automake-1.14
  pre_build:
    commands:
      - virtualenv venv
      - source venv/bin/activate && env && pip install -r requirements.txt
      - ls -l venv/lib/python2.7/site-packages
  build:
    commands:
      - chmod a+x ./pipeline-build.sh
      - ./pipeline-build.sh
  post_build:
    commands:
      - chmod a+x ./post-build.sh
      - ./post-build.sh
artifacts:
  type: zip
  files:
    - aws-lab-cafe.cfn
    - aws-lab-cafe-test.json
