version: 0.1

phases:
  # install:
  #   commands:
  #     - yum install -y binutils cracklib-devel gcc python27-devel zip
  #     - python2.7 ./get-pip.py
  #     - pip install awscli virtualenv
  pre_build:
    commands:
      - virtualenv venv
      - source venv/bin/activate && env && pip install -r requirements.txt
      - ls -l venv/lib/python2.7/site-packages
  build:
    commands:
      - ./pipeline-build.sh
  post_build:
    commands:
      - chmod a+x ./post-build.sh
      - ./post-build.sh
artifacts:
  type: zip
  files:
    - aws-lab-cafe.cfn
    - aws-lab-cafe-test.json
