version: 0.1

phases:
  install:
    commands:
      - chmod a+x ./codebuild
      - ./codebuild install
  pre_build:
    commands:
      - ./codebuild prebuild
  build:
    commands:
      - ./codebuild build
  post_build:
    commands:
      - ./codebuild postbuild
artifacts:
  type: zip
  files:
    - aws-lab-cafe.cfn
    - aws-lab-cafe-test.json
